### PR TITLE
fix little bug translation

### PR DESCRIPTION
**Pull request by cparrapa**
Hi @fontainejp 
Thanks i find the bug here and fixed, the problem is now for French it shows in English. :S

### CODE REVIEW

**Comment by fontainejp** [comment]
Hi,
sorry but it's not a good alternative 
i think this week i made a commit to fix it ;-)

**Comment by cparrapa** [comment]
Hi 
Yes not the best way to have the translations.
Is it possible to make the software for MAC or Linux as well?

**Comment by fontainejp** [comment]
it's possible to do it but i don't have mac(or linux) to test it. 
Perhaps with a virtual machine when i will have time...
see here --> https://www.electron.build/ for details
and change options in package.json
probably something like that
`build --mac
"dmg": {
      "contents": [
        {
          "x": 240,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },` 
for mac
test it and tell me
i will modify if it's ok

**Comment by cparrapa** [comment]
Sounds good i just have no experience packing with electron.
How to pass from web to packed?

**Comment by fontainejp** [comment]
Hi,
to understand how it works you must go here --> https://electronjs.org/docs/tutorial/first-app
a new release is available (more things are translated but not all)

**Comment by cparrapa** [comment]
thanks i will give a try

**Pull request closed without merging**
